{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "cdee2097-016b-403e-879f-e4a485b0fa76",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      " * Serving Flask app '__main__'\n",
      " * Debug mode: off\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.\n",
      " * Running on http://127.0.0.1:5000\n",
      "Press CTRL+C to quit\n",
      "[2024-08-30 22:13:55,046] ERROR in app: Exception on / [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\asas3\\anaconda3\\envs\\Rplot\\lib\\site-packages\\flask\\app.py\", line 1473, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\asas3\\anaconda3\\envs\\Rplot\\lib\\site-packages\\flask\\app.py\", line 883, in full_dispatch_request\n",
      "    return self.finalize_request(rv)\n",
      "  File \"C:\\Users\\asas3\\anaconda3\\envs\\Rplot\\lib\\site-packages\\flask\\app.py\", line 902, in finalize_request\n",
      "    response = self.make_response(rv)\n",
      "  File \"C:\\Users\\asas3\\anaconda3\\envs\\Rplot\\lib\\site-packages\\flask\\app.py\", line 1174, in make_response\n",
      "    raise TypeError(\n",
      "TypeError: The view function for 'home' did not return a valid response. The function either returned None or ended without a return statement.\n",
      "127.0.0.1 - - [30/Aug/2024 22:13:55] \"GET / HTTP/1.1\" 500 -\n",
      "127.0.0.1 - - [30/Aug/2024 22:13:55] \"GET /favicon.ico HTTP/1.1\" 404 -\n",
      "[2024-08-30 22:14:22,445] ERROR in app: Exception on / [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\asas3\\anaconda3\\envs\\Rplot\\lib\\site-packages\\flask\\app.py\", line 1473, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\asas3\\anaconda3\\envs\\Rplot\\lib\\site-packages\\flask\\app.py\", line 883, in full_dispatch_request\n",
      "    return self.finalize_request(rv)\n",
      "  File \"C:\\Users\\asas3\\anaconda3\\envs\\Rplot\\lib\\site-packages\\flask\\app.py\", line 902, in finalize_request\n",
      "    response = self.make_response(rv)\n",
      "  File \"C:\\Users\\asas3\\anaconda3\\envs\\Rplot\\lib\\site-packages\\flask\\app.py\", line 1174, in make_response\n",
      "    raise TypeError(\n",
      "TypeError: The view function for 'home' did not return a valid response. The function either returned None or ended without a return statement.\n",
      "127.0.0.1 - - [30/Aug/2024 22:14:22] \"GET / HTTP/1.1\" 500 -\n",
      "[2024-08-30 22:18:55,874] ERROR in app: Exception on / [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\asas3\\anaconda3\\envs\\Rplot\\lib\\site-packages\\flask\\app.py\", line 1473, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\asas3\\anaconda3\\envs\\Rplot\\lib\\site-packages\\flask\\app.py\", line 883, in full_dispatch_request\n",
      "    return self.finalize_request(rv)\n",
      "  File \"C:\\Users\\asas3\\anaconda3\\envs\\Rplot\\lib\\site-packages\\flask\\app.py\", line 902, in finalize_request\n",
      "    response = self.make_response(rv)\n",
      "  File \"C:\\Users\\asas3\\anaconda3\\envs\\Rplot\\lib\\site-packages\\flask\\app.py\", line 1174, in make_response\n",
      "    raise TypeError(\n",
      "TypeError: The view function for 'home' did not return a valid response. The function either returned None or ended without a return statement.\n",
      "127.0.0.1 - - [30/Aug/2024 22:18:55] \"GET / HTTP/1.1\" 500 -\n",
      "127.0.0.1 - - [30/Aug/2024 22:18:56] \"GET /favicon.ico HTTP/1.1\" 404 -\n",
      "[2024-08-30 22:20:02,077] ERROR in app: Exception on / [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\asas3\\anaconda3\\envs\\Rplot\\lib\\site-packages\\flask\\app.py\", line 1473, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\asas3\\anaconda3\\envs\\Rplot\\lib\\site-packages\\flask\\app.py\", line 883, in full_dispatch_request\n",
      "    return self.finalize_request(rv)\n",
      "  File \"C:\\Users\\asas3\\anaconda3\\envs\\Rplot\\lib\\site-packages\\flask\\app.py\", line 902, in finalize_request\n",
      "    response = self.make_response(rv)\n",
      "  File \"C:\\Users\\asas3\\anaconda3\\envs\\Rplot\\lib\\site-packages\\flask\\app.py\", line 1174, in make_response\n",
      "    raise TypeError(\n",
      "TypeError: The view function for 'home' did not return a valid response. The function either returned None or ended without a return statement.\n",
      "127.0.0.1 - - [30/Aug/2024 22:20:02] \"GET / HTTP/1.1\" 500 -\n",
      "[2024-08-30 22:20:02,407] ERROR in app: Exception on / [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\asas3\\anaconda3\\envs\\Rplot\\lib\\site-packages\\flask\\app.py\", line 1473, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\asas3\\anaconda3\\envs\\Rplot\\lib\\site-packages\\flask\\app.py\", line 883, in full_dispatch_request\n",
      "    return self.finalize_request(rv)\n",
      "  File \"C:\\Users\\asas3\\anaconda3\\envs\\Rplot\\lib\\site-packages\\flask\\app.py\", line 902, in finalize_request\n",
      "    response = self.make_response(rv)\n",
      "  File \"C:\\Users\\asas3\\anaconda3\\envs\\Rplot\\lib\\site-packages\\flask\\app.py\", line 1174, in make_response\n",
      "    raise TypeError(\n",
      "TypeError: The view function for 'home' did not return a valid response. The function either returned None or ended without a return statement.\n",
      "127.0.0.1 - - [30/Aug/2024 22:20:02] \"GET / HTTP/1.1\" 500 -\n",
      "[2024-08-30 22:20:02,529] ERROR in app: Exception on / [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\asas3\\anaconda3\\envs\\Rplot\\lib\\site-packages\\flask\\app.py\", line 1473, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\asas3\\anaconda3\\envs\\Rplot\\lib\\site-packages\\flask\\app.py\", line 883, in full_dispatch_request\n",
      "    return self.finalize_request(rv)\n",
      "  File \"C:\\Users\\asas3\\anaconda3\\envs\\Rplot\\lib\\site-packages\\flask\\app.py\", line 902, in finalize_request\n",
      "    response = self.make_response(rv)\n",
      "  File \"C:\\Users\\asas3\\anaconda3\\envs\\Rplot\\lib\\site-packages\\flask\\app.py\", line 1174, in make_response\n",
      "    raise TypeError(\n",
      "TypeError: The view function for 'home' did not return a valid response. The function either returned None or ended without a return statement.\n",
      "127.0.0.1 - - [30/Aug/2024 22:20:02] \"GET / HTTP/1.1\" 500 -\n",
      "[2024-08-30 22:20:02,591] ERROR in app: Exception on / [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\asas3\\anaconda3\\envs\\Rplot\\lib\\site-packages\\flask\\app.py\", line 1473, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\asas3\\anaconda3\\envs\\Rplot\\lib\\site-packages\\flask\\app.py\", line 883, in full_dispatch_request\n",
      "    return self.finalize_request(rv)\n",
      "  File \"C:\\Users\\asas3\\anaconda3\\envs\\Rplot\\lib\\site-packages\\flask\\app.py\", line 902, in finalize_request\n",
      "    response = self.make_response(rv)\n",
      "  File \"C:\\Users\\asas3\\anaconda3\\envs\\Rplot\\lib\\site-packages\\flask\\app.py\", line 1174, in make_response\n",
      "    raise TypeError(\n",
      "TypeError: The view function for 'home' did not return a valid response. The function either returned None or ended without a return statement.\n",
      "127.0.0.1 - - [30/Aug/2024 22:20:02] \"GET / HTTP/1.1\" 500 -\n",
      "127.0.0.1 - - [30/Aug/2024 22:20:03] \"GET /favicon.ico HTTP/1.1\" 404 -\n",
      "127.0.0.1 - - [30/Aug/2024 22:20:03] \"GET /favicon.ico HTTP/1.1\" 404 -\n",
      "[2024-08-30 22:21:26,566] ERROR in app: Exception on / [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\asas3\\anaconda3\\envs\\Rplot\\lib\\site-packages\\flask\\app.py\", line 1473, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\asas3\\anaconda3\\envs\\Rplot\\lib\\site-packages\\flask\\app.py\", line 883, in full_dispatch_request\n",
      "    return self.finalize_request(rv)\n",
      "  File \"C:\\Users\\asas3\\anaconda3\\envs\\Rplot\\lib\\site-packages\\flask\\app.py\", line 902, in finalize_request\n",
      "    response = self.make_response(rv)\n",
      "  File \"C:\\Users\\asas3\\anaconda3\\envs\\Rplot\\lib\\site-packages\\flask\\app.py\", line 1174, in make_response\n",
      "    raise TypeError(\n",
      "TypeError: The view function for 'home' did not return a valid response. The function either returned None or ended without a return statement.\n",
      "127.0.0.1 - - [30/Aug/2024 22:21:26] \"GET / HTTP/1.1\" 500 -\n",
      "[2024-08-30 22:21:35,109] ERROR in app: Exception on / [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\asas3\\anaconda3\\envs\\Rplot\\lib\\site-packages\\flask\\app.py\", line 1473, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\asas3\\anaconda3\\envs\\Rplot\\lib\\site-packages\\flask\\app.py\", line 883, in full_dispatch_request\n",
      "    return self.finalize_request(rv)\n",
      "  File \"C:\\Users\\asas3\\anaconda3\\envs\\Rplot\\lib\\site-packages\\flask\\app.py\", line 902, in finalize_request\n",
      "    response = self.make_response(rv)\n",
      "  File \"C:\\Users\\asas3\\anaconda3\\envs\\Rplot\\lib\\site-packages\\flask\\app.py\", line 1174, in make_response\n",
      "    raise TypeError(\n",
      "TypeError: The view function for 'home' did not return a valid response. The function either returned None or ended without a return statement.\n",
      "127.0.0.1 - - [30/Aug/2024 22:21:35] \"GET / HTTP/1.1\" 500 -\n",
      "[2024-08-30 22:33:02,998] ERROR in app: Exception on / [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\asas3\\anaconda3\\envs\\Rplot\\lib\\site-packages\\flask\\app.py\", line 1473, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\asas3\\anaconda3\\envs\\Rplot\\lib\\site-packages\\flask\\app.py\", line 883, in full_dispatch_request\n",
      "    return self.finalize_request(rv)\n",
      "  File \"C:\\Users\\asas3\\anaconda3\\envs\\Rplot\\lib\\site-packages\\flask\\app.py\", line 902, in finalize_request\n",
      "    response = self.make_response(rv)\n",
      "  File \"C:\\Users\\asas3\\anaconda3\\envs\\Rplot\\lib\\site-packages\\flask\\app.py\", line 1174, in make_response\n",
      "    raise TypeError(\n",
      "TypeError: The view function for 'home' did not return a valid response. The function either returned None or ended without a return statement.\n",
      "127.0.0.1 - - [30/Aug/2024 22:33:03] \"GET / HTTP/1.1\" 500 -\n",
      "[2024-08-30 22:33:46,751] ERROR in app: Exception on / [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\asas3\\anaconda3\\envs\\Rplot\\lib\\site-packages\\flask\\app.py\", line 1473, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\asas3\\anaconda3\\envs\\Rplot\\lib\\site-packages\\flask\\app.py\", line 883, in full_dispatch_request\n",
      "    return self.finalize_request(rv)\n",
      "  File \"C:\\Users\\asas3\\anaconda3\\envs\\Rplot\\lib\\site-packages\\flask\\app.py\", line 902, in finalize_request\n",
      "    response = self.make_response(rv)\n",
      "  File \"C:\\Users\\asas3\\anaconda3\\envs\\Rplot\\lib\\site-packages\\flask\\app.py\", line 1174, in make_response\n",
      "    raise TypeError(\n",
      "TypeError: The view function for 'home' did not return a valid response. The function either returned None or ended without a return statement.\n",
      "127.0.0.1 - - [30/Aug/2024 22:33:46] \"GET / HTTP/1.1\" 500 -\n",
      "[2024-08-30 22:33:58,535] ERROR in app: Exception on / [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\asas3\\anaconda3\\envs\\Rplot\\lib\\site-packages\\flask\\app.py\", line 1473, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\asas3\\anaconda3\\envs\\Rplot\\lib\\site-packages\\flask\\app.py\", line 883, in full_dispatch_request\n",
      "    return self.finalize_request(rv)\n",
      "  File \"C:\\Users\\asas3\\anaconda3\\envs\\Rplot\\lib\\site-packages\\flask\\app.py\", line 902, in finalize_request\n",
      "    response = self.make_response(rv)\n",
      "  File \"C:\\Users\\asas3\\anaconda3\\envs\\Rplot\\lib\\site-packages\\flask\\app.py\", line 1174, in make_response\n",
      "    raise TypeError(\n",
      "TypeError: The view function for 'home' did not return a valid response. The function either returned None or ended without a return statement.\n",
      "127.0.0.1 - - [30/Aug/2024 22:33:58] \"GET / HTTP/1.1\" 500 -\n",
      "127.0.0.1 - - [30/Aug/2024 22:33:59] \"GET /favicon.ico HTTP/1.1\" 404 -\n",
      "[2024-08-30 22:41:39,892] ERROR in app: Exception on / [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\asas3\\anaconda3\\envs\\Rplot\\lib\\site-packages\\flask\\app.py\", line 1473, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\asas3\\anaconda3\\envs\\Rplot\\lib\\site-packages\\flask\\app.py\", line 883, in full_dispatch_request\n",
      "    return self.finalize_request(rv)\n",
      "  File \"C:\\Users\\asas3\\anaconda3\\envs\\Rplot\\lib\\site-packages\\flask\\app.py\", line 902, in finalize_request\n",
      "    response = self.make_response(rv)\n",
      "  File \"C:\\Users\\asas3\\anaconda3\\envs\\Rplot\\lib\\site-packages\\flask\\app.py\", line 1174, in make_response\n",
      "    raise TypeError(\n",
      "TypeError: The view function for 'home' did not return a valid response. The function either returned None or ended without a return statement.\n",
      "127.0.0.1 - - [30/Aug/2024 22:41:39] \"GET / HTTP/1.1\" 500 -\n",
      "[2024-08-30 22:41:51,908] ERROR in app: Exception on / [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\asas3\\anaconda3\\envs\\Rplot\\lib\\site-packages\\flask\\app.py\", line 1473, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\asas3\\anaconda3\\envs\\Rplot\\lib\\site-packages\\flask\\app.py\", line 883, in full_dispatch_request\n",
      "    return self.finalize_request(rv)\n",
      "  File \"C:\\Users\\asas3\\anaconda3\\envs\\Rplot\\lib\\site-packages\\flask\\app.py\", line 902, in finalize_request\n",
      "    response = self.make_response(rv)\n",
      "  File \"C:\\Users\\asas3\\anaconda3\\envs\\Rplot\\lib\\site-packages\\flask\\app.py\", line 1174, in make_response\n",
      "    raise TypeError(\n",
      "TypeError: The view function for 'home' did not return a valid response. The function either returned None or ended without a return statement.\n",
      "127.0.0.1 - - [30/Aug/2024 22:41:51] \"GET / HTTP/1.1\" 500 -\n",
      "[2024-08-30 22:42:03,449] ERROR in app: Exception on / [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\asas3\\anaconda3\\envs\\Rplot\\lib\\site-packages\\flask\\app.py\", line 1473, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\asas3\\anaconda3\\envs\\Rplot\\lib\\site-packages\\flask\\app.py\", line 883, in full_dispatch_request\n",
      "    return self.finalize_request(rv)\n",
      "  File \"C:\\Users\\asas3\\anaconda3\\envs\\Rplot\\lib\\site-packages\\flask\\app.py\", line 902, in finalize_request\n",
      "    response = self.make_response(rv)\n",
      "  File \"C:\\Users\\asas3\\anaconda3\\envs\\Rplot\\lib\\site-packages\\flask\\app.py\", line 1174, in make_response\n",
      "    raise TypeError(\n",
      "TypeError: The view function for 'home' did not return a valid response. The function either returned None or ended without a return statement.\n",
      "127.0.0.1 - - [30/Aug/2024 22:42:03] \"GET / HTTP/1.1\" 500 -\n",
      "127.0.0.1 - - [30/Aug/2024 22:42:04] \"GET /favicon.ico HTTP/1.1\" 404 -\n"
     ]
    }
   ],
   "source": [
    "from flask import Flask\n",
    "\n",
    "app = Flask(__name__)\n",
    "\n",
    "@app.route(\"/\")\n",
    "def home():\n",
    "    return \n",
    "\n",
    "app.run()"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.19"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
